name: Hackathon - Links and Navigation Checks

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run checks from'
        required: true
        default: 'main'
        type: string

jobs:
  validate:
    name: Validate Links and Navigation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  # Faster and stricter than npm install

      - name: Build navigation artifacts
        run: npm run buildNavigation

      - name: Normalize and check links
        run: |
          npm run normalizeLinks
          npm run checkLinks
