---
name: Generate AI Summary
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment to deploy to"
        type: choice
        required: true
        default: "stage"
        options:
          - stage
          - prod
          - stage & prod
      baseSha:
        description: "Use base SHA commit to deploy from (empty string defaults to last commit before HEAD)"
        type: string
        required: false
        default: ""
      deployAll:
        description: "Force deploy all files"
        type: boolean
        default: false
      generateAISummary:
        description: "Generate AI Summary"
        type: boolean
        default: true
jobs:
  deployment:
    name: Generate AI Summary
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/generateSummary.yml@ai
    with:
      env: ${{ inputs.env }}
      baseSha: ${{ inputs.baseSha }}
      deployAll: ${{ inputs.deployAll }}
      generateAISummary: ${{ inputs.generateAISummary }}
    secrets:
      ADP_CHATGPT_API_KEY: ${{ secrets.ADP_DUMMY }}