---
name: PR Tests
on:
  pull_request:
    branches:
      - main
      - stage
  push:
    branches:
      - main
      - stage

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Lint
        run: npx --yes github:AdobeDocs/adp-devsite-utils runLint -v

  link-check:
    name: Link Check
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Check Links
        run: yarn test:links

