---
name: PR Tests
on:
  pull_request:
    branches:
      - main
      - stage
  push:
    branches:
      - main
      - stage

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lint
        run: npx --yes github:AdobeDocs/adp-devsite-utils runLint -v

