---
name: Call Validate PR Workflow
on:
  pull_request:
  workflow_dispatch:
    branches: [main]
    paths:
      - 'src/pages/**'
  push:
    branches:
      - main
      - stage

jobs:
  call-validation:
    name: Validate PR
    call-validation:
      uses: AdobeDocs/adp-devsite-workflow/.github/workflows/validate-pr.yml@DEVSITE-1978-linter-bug
