---
name: Latest Pull Request
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/pages/**'
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Utils Repo
        uses: actions/checkout@v4
        with:
          repository: AdobeDocs/adp-devsite-utils
          path: utils
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Enable Corepack for Yarn v3
        run: corepack enable
        
      - name: Install Yarn v3
        uses: borales/actions-yarn@v3
        with:
          cmd: set version stable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        uses: borales/actions-yarn@v3
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          YARN_ENABLE_HARDENED_MODE: false
        with:
          cmd: install --mode=update-lockfile

      - name: Install utils dependencies
        run: |
          cd ./utils
          npm install

      - name: Lint
        run: node ./dummy-lint.js

      - name: Present Working Directory
        run: pwd

      - name: List Utils Directory
        run: ls -la ./utils/bin/

      - name: Check Links
        uses: actions/github-script@v7
        with:
          script: |
            const checkLinks = require('./utils/bin/checkLinks.js');
            await checkLinks();

