---
name: Latest Pull Request
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/pages/**'
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: node ./dummy-lint.js

      - name: Check Links
        run: node ./dummy-check-links.js



