---
###########################
###########################
## Pull request testing ##
###########################
###########################
name: Latest Pull Request

# Documentation:
# - Workflow: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# - Markdown linter: https://github.com/DavidAnson/markdownlint
# - Link validation: https://github.com/remarkjs/remark-validate-links

######################################################
# Start the job on a pull request to the main branch #
######################################################
on:
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  validate:
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node v16 for Yarn v3
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0' # Current LTS version

      - name: Enable Corepack for Yarn v3
        run: corepack enable

      - name: Install Yarn v3
        uses: borales/actions-yarn@v3
        with:
          cmd: set version stable

      - name: Install dependencies
        uses: borales/actions-yarn@v3
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        with:
          cmd: install

      - name: Lint Markdown files
        run: |
          # Run linting and capture output
          yarn lint 2>&1 | tee lint-output.txt
          
          # Check if there are any critical errors (MD009, MD012, MD013, MD041)
          if grep -q "MD009\|MD012\|MD013\|MD041" lint-output.txt; then
            echo "❌ Found critical errors - PR validation failed"
            cat lint-output.txt
            exit 1
          fi
          
          # Check for warning-level violations (MD025, MD024, MD026)
          if grep -q "MD025\|MD024\|MD026" lint-output.txt; then
            echo "⚠️ Found style warnings (these won't fail the PR):"
            grep "MD025\|MD024\|MD026" lint-output.txt || true
          fi
          
          echo "✅ Linting completed successfully"

      - name: Check internal links
        uses: borales/actions-yarn@v3
        with:
          cmd: test:links

      - name: Build site
        if: ${{ success() }}
        uses: borales/actions-yarn@v3
        with:
          cmd: build
