---
name: Test Links
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/pages/**'

jobs:
  test-links:
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/deploy.yml@devsite-1761-test-link