---
name: Latest Pull Request
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/pages/**'
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Utils Repo
        uses: actions/checkout@v4
        with:
          repository: AdobeDocs/adp-devsite-utils
          path: utils
          ref: main

      - name: Lint
        run: node ./dummy-lint.js

      - name: List Utils Directory
        run: pwd

      - name: List Utils Directory
        run: ls -la ./utils/bin/

      - name: Check Links
        uses: actions/github-script@v7
        with:
          script: |
            const checkLinks = require('./utils/bin/checkLinks.js');
            await checkLinks();



